networks:
  domibus-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${NET_PREFIX:-172.20.0}.0/24

services:
  domibus-blue-db:
    build:
      context: .
      dockerfile: domibus-db.Dockerfile
    container_name: domibus-blue-db
    ports:
        - "127.0.0.1:${DOMIBUS_BLUE_DB_PORT:-8301}:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1" ]
      interval: 5s
      timeout: 5s
      retries: 30
    networks:
      domibus-network:
        ipv4_address: ${NET_PREFIX:-172.20.0}.10

  domibus-red-db:
    build:
      context: .
      dockerfile: domibus-db.Dockerfile
    container_name: domibus-red-db
    ports:
        - "127.0.0.1:${DOMIBUS_RED_DB_PORT:-8302}:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1" ]
      interval: 5s
      timeout: 5s
      retries: 30
    networks:
      domibus-network:
        ipv4_address: ${NET_PREFIX:-172.20.0}.11

  domismp-db:
    build:
      context: .
      dockerfile: domismp-db.Dockerfile
    container_name: domismp-db
    ports:
        - "127.0.0.1:${DOMISMP_DB_PORT:-8303}:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1" ]
      interval: 5s
      timeout: 5s
      retries: 30
    networks:
      domibus-network:
        ipv4_address: ${NET_PREFIX:-172.20.0}.12

  domisml-db:
    build:
      context: .
      dockerfile: domisml-db.Dockerfile
    container_name: domisml-db
    ports:
        - "127.0.0.1:${DOMISML_DB_PORT:-8304}:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1" ]
      interval: 5s
      timeout: 5s
      retries: 30
    networks:
      domibus-network:
        ipv4_address: ${NET_PREFIX:-172.20.0}.13

  domibus-blue:
    build:
      context: .
      dockerfile: domibus.Dockerfile
    container_name: domibus-blue
    environment:
      - DOMIBUS_DB_HOST=domibus-blue-db
      - DOMIBUS_KEY_ALIAS=blue_gw
      - DOMIBUS_SMLZONE=hr.test.eracun.local
    ports:
      - "127.0.0.1:${DOMIBUS_BLUE_PORT:-8081}:8080"
    volumes:
      - "./logs/blue:/opt/domibus/logs"
    depends_on:
      domibus-blue-db:
        condition: service_healthy
    dns:
      - ${NET_PREFIX:-172.20.0}.2
    networks:
      domibus-network:
        ipv4_address: ${NET_PREFIX:-172.20.0}.20

  domibus-red:
    build:
      context: .
      dockerfile: domibus.Dockerfile
    container_name: domibus-red
    environment:
      - DOMIBUS_DB_HOST=domibus-red-db
      - DOMIBUS_KEY_ALIAS=red_gw
      - DOMIBUS_SMLZONE=hr.test.eracun.local
    ports:
      - "127.0.0.1:${DOMIBUS_RED_PORT:-8082}:8080"
    volumes:
      - "./logs/red:/opt/domibus/logs"
    depends_on:
      domibus-red-db:
        condition: service_healthy
    dns:
      - ${NET_PREFIX:-172.20.0}.2
    networks:
      domibus-network:
        ipv4_address: ${NET_PREFIX:-172.20.0}.21

  domismp:
    build:
      context: .
      dockerfile: domismp.Dockerfile
    container_name: domismp
    ports:
      - "127.0.0.1:${DOMISMP_PORT:-8083}:8080"
    volumes:
      - "./logs/smp:/opt/smp/logs"
    depends_on:
      domismp-db:
        condition: service_healthy
    dns:
      - ${NET_PREFIX:-172.20.0}.2
    networks:
      domibus-network:
        ipv4_address: ${NET_PREFIX:-172.20.0}.30

  domisml:
    build:
      context: .
      dockerfile: domisml.Dockerfile
    container_name: domisml
    ports:
      - "127.0.0.1:${DOMISML_PORT:-8084}:8080"
    volumes:
      - "./logs/sml:/opt/sml/logs"
    depends_on:
      domisml-db:
        condition: service_healthy
      bind9:
        condition: service_started
    dns:
      - ${NET_PREFIX:-172.20.0}.2
    networks:
      domibus-network:
        ipv4_address: ${NET_PREFIX:-172.20.0}.31

  bind9:
    build:
      context: .
      dockerfile: bind9.Dockerfile
    container_name: bind9
    networks:
      domibus-network:
        ipv4_address: ${NET_PREFIX:-172.20.0}.2
        
  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    container_name: client
    dns:
      - ${NET_PREFIX:-172.20.0}.2
    networks:
      domibus-network:
        ipv4_address: ${NET_PREFIX:-172.20.0}.100
    ports:
      - "127.0.0.1:${CLIENT_PORT:-3000}:3000"
